disabled_rules:
  - file_length
  - function_parameter_count
  - nesting
  - non_optional_string_data_conversion
  - opening_brace
  - unused_closure_parameter
  - unused_optional_binding
  # Nice to haves
  - cyclomatic_complexity
  - function_body_length
analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import
opt_in_rules:
  - balanced_xctest_lifecycle
  - closure_spacing
  - closure_end_indentation
  - collection_alignment
  - comment_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - empty_count
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - number_separator
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_key_path
  - prefer_self_type_over_type_of_self
  - private_swiftui_state
  - prohibited_super_call
  - private_outlet
  - private_subject
  - private_unit_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - self_binding
  - shorthand_argument
  - single_test_class
  - shorthand_optional_binding
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
excluded:
  - Pods
  - .build

type_name:
  excluded:
    - ID
  max_length:
    warning: 50
    error: 60
modifier_order:
  preferred_modifier_order: [acl, override]
identifier_name:
  excluded:
    - id
    - to
trailing_comma:
  mandatory_comma: true
trailing_whitespace:
  ignores_empty_lines: true
trailing_closure:
  only_single_muted_parameter: true
large_tuple:
  warning: 3
  error: 4
line_length:
  warning: 200

deployment_target:
  iOS_deployment_target: 14
  tvOS_deployment_target: 14
  watchOS_deployment_target: 7
  macOS_deployment_target: 11
  visionOS_deployment_target: 1
