name: build

on:
  push:
    branches: [main]
  pull_request:
    branches:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - watchOS
          - macOS
          - visionOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: mxcl/xcodebuild@v3
        with:
          platform: ${{ matrix.platform }}
          scheme: FetchRequests-${{ matrix.platform }}
          swift: ~6.0
          action: test
          code-coverage: true
      - name: Code Coverage
        #uses: codecov/codecov-action@v2
        run: bash <(curl -s https://codecov.io/bash);
  validate:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swift Lint
        run: |
          command -v swiftlint || brew install --quiet swiftlint
          swiftlint --reporter github-actions-logging --strict
      - name: Swift Format
        run: |
          command -v swiftformat || brew install --quiet swiftformat
          swiftformat --reporter github-actions-log --lint .
      - name: Pod Lint
        run: pod lib lint --quick --fail-fast --verbose --skip-tests
      - name: Example Project
        uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          scheme: iOS Example
          swift: ~6.0
          action: build
          working-directory: Example
