name: build

on:
  push:
    branches: [main]
  pull_request:
    branches:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          #- watchOS
          - macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          scheme: FetchRequests-${{ matrix.platform }}
          action: test
          code-coverage: true
      - name: LS
        run: ls -R test.xcresult
      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          searchPath: ~/Library/Developer/Xcode/DerivedData
          #files: ./coverage1.xml,./coverage2.xml # optional
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
  validate:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swift Lint
        run: swiftlint
      - name: Pod Lint
        run: pod lib lint --quick --fail-fast --verbose --skip-tests
      - name: Example Project
        uses: mxcl/xcodebuild@v1
        with:
          platform: iOS
          scheme: iOS Example
          action: build
          warnings-as-errors: true
          working-directory: Example
