name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  build:
    strategy:
      matrix:
        platform:
          - iOS
          - tvOS
          - watchOS
          - macOS
    runs-on: macos-latest
    needs: checkout
    steps:
      - name: Build
        uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          scheme: FetchRequests-${{ matrix.platform }}
          #action: test
          code-coverage: true
          #warnings-as-errors: true
  lint:
    runs-on: macos-latest
    needs: build
      - name: Pod Lint
        run: pod lib lint --quick --fail-fast --verbose --skip-tests
  example
    runs-on: macos-latest
    needs: build
      - name: Build
        uses: mxcl/xcodebuild@v1
        with:
          platform: iOS
          scheme: iOS Example
          action: build
          warnings-as-errors: true
          working-directory: Example
